/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    IBiBarChartLineFill: typeof import('~icons/bi/bar-chart-line-fill')['default']
    IBiBatteryFull: typeof import('~icons/bi/battery-full')['default']
    IBiCamera: typeof import('~icons/bi/camera')['default']
    IBiCameraVideo: typeof import('~icons/bi/camera-video')['default']
    IBiCameraVideoOff: typeof import('~icons/bi/camera-video-off')['default']
    IBiCircleFill: typeof import('~icons/bi/circle-fill')['default']
    IBiHouseDoor: typeof import('~icons/bi/house-door')['default']
    IBiImages: typeof import('~icons/bi/images')['default']
    IBiWifi: typeof import('~icons/bi/wifi')['default']
    IBiWifiOff: typeof import('~icons/bi/wifi-off')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
